services:  
  postgres_dev:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: appdb
    networks: 
      - alloy-net
    command: >
      postgres -c logging_collector=on
               -c log_directory='log'
               -c log_filename='postgresql.log'
               -c log_statement='all'
               -c log_destination='csvlog,stderr'
               -c log_min_messages=info
               -c log_rotation_age=0
               -c log_rotation_size=0
               -c log_truncate_on_rotation=off

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    env_file: 
      - .env
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - postgres-data:/var/lib/postgresql/data:ro
    command: run /etc/alloy/config.alloy
    networks:
      - alloy-net
    depends_on:
      # - loki
      - postgres_dev

volumes:
  postgres-data:
  alloy_data:
  # prometheus_data:
  # grafana_data:

networks:
  alloy-net:
    driver: bridge
