global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'alloy'
  #   static_configs:
  #     - targets: ['alloy:12345']
  #
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']



