services:  
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    networks: 
      - alloy-net
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    networks: 
      - alloy-net 
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    networks: 
      - alloy-net
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana


volumes:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  alloy-net:
    driver: bridge
