services:  
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: testdb
    networks: 
      - alloy-net
      - db-net
    command: >
      postgres -c logging_collector=on
               -c log_directory='log'
               -c log_filename='postgresql.log'
               -c log_statement='mod'
               -c log_destination='csvlog,stderr'
               -c log_min_messages=info
               -c log_rotation_age=0
               -c log_rotation_size=0
               -c log_truncate_on_rotation=off

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://root:example@postgres:5432/testdb?sslmode=disable
    volumes:
      - ../db/migrations:/db/migrations
    networks:
      - db-net
    command: ["--wait","up"]

  alloy:
    image: grafana/alloy:latest
    env_file: 
      - ../.env
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - postgres-data:/var/lib/postgresql/data:ro
    command: run /etc/alloy/config.alloy
    networks:
      - alloy-net
    depends_on:
      - postgres

volumes:
  postgres-data:
  alloy-data:

networks:
  alloy-net:
    driver: bridge

  db-net:
    driver: bridge
